config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get '/taco' => "taco#show"
  resources :tags
  resources :images
  root to: 'static#home'
  resources :users do
    resources :images
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to (:user )
  has_and_belongs_to_many (:users)
  has_and_belongs_to_many (:tags)
  has_one_attached :image_upload

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin, only: [:destroy]

  # GET /images
  def index
    @images = Image.all
  end


  def show
    @user = current_user
    @tags = Tag.all
    @tag_array = []
    @tags.each do |tag|
      @tag_array.push(tag) if @image.tags.exclude?(tag)
    end
    # binding.pry
  end

  # GET /images/new
  def new
    @user = current_user
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
    @user = current_user
  end

  # POST /images
  def create
    @image = Image.new(image_params)
    @user = current_user
    # binding.pry
    if @image.save
      redirect_to @image, notice: 'Image was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /images/1
  def update

    @image = Image.find(params[:id])
    if params[:image]
      if params[:image].fetch("favorite") == "1"
        @image.update_attribute(:favorite, true)
        redirect_to image_path(@image)
        return
      elsif params[:image].fetch("favorite") == "0"
        @image.update_attribute(:favorite, false)
        redirect_to image_path(@image)
        return
      end
    end

    if params[:tags]
      if
        @tag = Tag.find(params[:tags].fetch("name").to_i)
        @image.tags << @tag
        redirect_to image_path(@image)
        return
      end
    end


    if @image.update(image_params)
      redirect_to @image, notice: 'Image was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /images/1
  def destroy
    @image.destroy
    redirect_to images_url, notice: 'Image was successfully destroyed.'
  end

  def add
    @image = Image.find(params[:id])
    # Division.where(name: employee_params.fetch("division_id")).first.id)
    tag = Tag.find()
    # binding.pry
    @image.tags << tag
    flash[:notice] = "Tag Added"
    redirect_to image_path(@image)

  end



  private
  # Use callbacks to share common setup or constraints between actions.
  def set_image
    @image = Image.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def image_params
    params.require(:image).permit(:img, :user_id, :favorite, :image_upload, :image, :id)
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_with(model: image, local: true) do |form| %>
<% if image.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

  <ul>
    <% image.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :img %>
  <%= form.text_field :img %>
</div>

<div class="field">
  <%= form.file_field :image_upload %>
  <%= form.hidden_field :user_id, :value => @user.id %>
</div>

<div class="field">
  <%= form.label :favorite %>
  <%= form.check_box :favorite %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Images</h1>

<table>
  <thead>
    <tr>
      <th>Img</th>
      <th>User</th>
      <th>Favorite</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.img %></td>
        <td><%= image.user_id %></td>
        <td><%= image.favorite %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>



<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Img:</strong>
  <%= image_tag @image.image_upload %>
</p>

<p>
  <strong>User:</strong>
  <%= @image.user_id %>
</p>

<p>
  <strong>Favorite:</strong>
  <%= @image.favorite %>
</p>

<strong>Tags:</strong>
<ul>
  <% array = []%>

  <% @image.tags.each do |tag| %>
  <% if (array.exclude?(tag.name)) || (array.any? == false)%>

    <li><%= tag.name %></li>
      <% array.push(tag.name)%>
    <% end %>
  <% end %>
</ul>



<%= form_for @image do |f| %>
    <%= f.label "Add as a favorite" %> <br />
    <%= f.check_box :favorite %> <br />
    <p><%= f.submit :Submit, class: 'btn btn-primary'  %></p>
<% end %>


<% if @tag_array.any? %>
<%= form_for @image do |f| %>
<%= collection_select(:tags, :name, @tag_array, :id, :name) %>
  <p><%= f.submit :Submit, class: 'btn btn-primary'  %></p>
  <% end %>
  <% end %>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>